apiVersion: v1
kind: ConfigMap
metadata:
  name: user-activity-config
  namespace: user-activity
data:
  MONGO_URL: mongodb://mongodb:27017
  MONGO_DATABASE: user_activity
  KAFKA_BROKERS: redpanda:9092
  KAFKA_TOPIC: user-activity
  KAFKA_GROUP_ID: user-activity-consumers
